import { lazy } from 'react';

export const SignIn = lazy(() => import('../pages/SignIn/SignIn'));
export const Registration = lazy(() => import('../pages/Registration/Registration'));
export const StudentCourses = lazy(() => import('../pages/Courses/StudentCourses/StudentCourses'));
export const TeacherCourses = lazy(() => import('../pages/Courses/TeacherCourses/TeacherCourses'));
export const AdminCourses = lazy(() => import('../pages/Courses/AdminCourses/AdminCourses'));
export const AdminStudents = lazy(() => import('../pages/Students/AdminStudents/AdminStudents'));
export const AdminGroups = lazy(() => import('../pages/Groups/AdminGroups/AdminGroups'));
export const AdminTeachers = lazy(() => import('../pages/Teachers/AdminTeachers/AdminTeachers'));
export const TeacherLessons = lazy(() => import('../pages/Lessons/TeacherLessons/TeacherLessons'));
export const TeacherAssignments = lazy(() => import('../pages/Assignments/TeacherAssignments/TeacherAssignments'));
export const TeacherSubmissions = lazy(() => import('../pages/Submissions/TeacherSubmissions/TeacherSubmissions'));
export const TeacherSubmission = lazy(() => import('../pages/Submissions/TeacherSubmission/TeacherSubmission'));
export const StudentLessons = lazy(() => import('../pages/Lessons/StudentLessons/StudentLessons'));
export const StudentAssignments = lazy(() => import('../pages/Assignments/StudentAssignments/StudentAssignments'));
export const StudentAssignment = lazy(() => import('../pages/Assignments/StudentAssignment/StudentAssignment'));
export const StudentSubmissions = lazy(() => import('../pages/Submissions/StudentSubmissions/StudentSubmissions'));
export const AccountantTuitionFees = lazy(() => import('../pages/TuitionFees/AccountantTuitionFees/AccountantTuitionFees'));
export const AccountantPayments = lazy(() => import('../pages/Payments/AccountantPayments/AccountantPayments'));
export const ParentStudents = lazy(() => import('../pages/Students/ParentStudents/ParentStudents'));
export const ParentsAttendances = lazy(() => import('../pages/Attendances/ParentsAttendances/ParentsAttendances'));
export const ParentsLessons = lazy(() => import('../pages/Lessons/ParentsLessons/ParentsLessons'));
export const ParentsAssignments = lazy(() => import('../pages/Assignments/ParentsAssignments/ParentsAssignments'));
export const ParentsAssignment = lazy(() => import('../pages/Assignments/ParentsAssignment/ParentsAssignment'));
export const ParentsTuitionFees = lazy(() => import('../pages/TuitionFees/ParentsTuitionFees/ParentsTuitionFees'));
export const ParentsPayments = lazy(() => import('../pages/Payments/ParentsPayments/ParentsPayments'));
export const TeacherAttendances = lazy(() => import('../pages/Attendances/TeacherAttendances/TeacherAttendances'));
